// <auto-generated />
namespace MovieCustomerMvcAppWithAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class GenreIdmadeasForeignKeyinmovietable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GenreIdmadeasForeignKeyinmovietable));
        
        string IMigrationMetadata.Id
        {
            get { return "202008240649462_GenreId made as Foreign Key in movie table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
